env:
  node: true
  es2021: true
  jest: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-console: 0
  import/extensions: 0
  no-underscore-dangle: 0
  max-len: 0
  arrow-body-style: 0
  import/order: 0
  no-trailing-spaces: 0
  eol-last: 0
  semi: [2, never]  # Нет точек с запятой
  quotes: [2, single]  # Одинарные кавычки
